model: CelebA
dataset_path: /scratch/itee/uqsswain/datasets/CelebA/

classifiers:
  celeba_cnn_1: /scratch/itee/uqsswain/artifacts/spaa/classifiers/celeba/lightning_logs/version_546423/checkpoints/epoch=9-step=11720.ckpt

autoencoders:
  cnn_128: /scratch/itee/uqsswain/artifacts/spaa/autoencoders/celeba/lightning_logs/version_546284/checkpoints/epoch=19-step=23440.ckpt

miscs:
  nb_classes: 2
  min_pixel_value: 0.0
  max_pixel_value: 1.0
  reshape:
    - 128
    - 128
  input_shape:
    - 128
    - 128

attack_kwargs:
  fgsm_orig:
    norm: inf
    eps: 0.5
  fgsm_modf:
    norm: inf
    eps: 0.2
  pgd_orig:
    norm: inf
    eps: 0.1
  pgd_modf:
    norm: inf
    eps: 0.01
  bim_orig:
    norm: inf
    eps: 0.1
  bim_modf:
    norm: inf
    eps: 0.01
  cnw_orig: {}
  cnw_modf: {}
  deepfool_orig:
    epsilon: 0.001
    nb_grads: 10
  deepfool_modf:
    epsilon: 0.001
    nb_grads: 10
  elastic_orig:
    targeted: false
  elastic_modf:
    targeted: false
