model: GTSRB
dataset_path: /scratch/itee/uqsswain/datasets/GTSRB/

classifiers:
  gtsrb_cnn_1: /scratch/itee/uqsswain/artifacts/spaa/classifiers/gtsrb/lightning_logs/version_546496/checkpoints/epoch=24-step=4250.ckpt
autoencoders:
  cnn_128: /scratch/itee/uqsswain/artifacts/spaa/autoencoders/gtsrb/lightning_logs/version_546654/checkpoints/epoch=49-step=1100.ckpt

miscs:
  nb_classes: 43
  min_pixel_value: 0.0
  max_pixel_value: 1.0
  reshape:
    - 32
    - 32
  input_shape:
    - 32
    - 32

art_attack_kwargs:
  fgsm_orig:
    norm: inf
    eps: 0.5
  fgsm_modf:
    norm: inf
    eps: 0.2
  pgd_orig:
    norm: inf
    eps: 0.5
  pgd_modf:
    norm: inf
    eps: 0.2
  bim_orig:
    eps: 0.5
  bim_modf:
    eps: 0.2
  cnw_orig: {}
  cnw_modf: {}
  deepfool_orig:
    epsilon: 0.001
    nb_grads: 10
  deepfool_modf:
    epsilon: 0.001
    nb_grads: 10
  elastic_orig:
    targeted: false
  elastic_modf:
    targeted: false
