model: IMAGENET
dataset_path:

classifiers:
  imagenet_inceptionv3: "none"
autoencoders:
  vgg_16: "/scratch/itee/uqsswain/models/imagenet-vgg16.pth"

miscs:
  nb_classes: 1000
  min_pixel_value: -2.117904
  max_pixel_value: 2.248908
  reshape:
    - 3
    - 224
    - 224
  input_shape:
    - 3
    - 224
    - 224

attack_kwargs:
  fgsm_orig:
    norm: inf
    eps: 0.2
  fgsm_modf:
    norm: inf
    eps: 0.0001
  pgd_orig:
    norm: inf
    eps: 0.1
  pgd_modf:
    norm: inf
    eps: 0.0001
  bim_orig:
    norm: inf
    eps: 0.1
  bim_modf:
    norm: inf
    eps: 0.01
  cnw_orig:
  cnw_modf:
  deepfool_orig:
    # epsilon: 0.001
    # nb_grads: 5
    steps: 50
  deepfool_modf:
    # epsilon: 0.001
    # nb_grads: 5
    steps: 50
    overshoot: 0.0002
  elastic_orig:
    targeted: false
  elastic_modf:
    targeted: false
