model: IMAGENET
dataset_path:

classifiers:
  imagenet_inceptionv3: "none"
autoencoders:
  vgg_16: "/scratch/itee/uqsswain/models/imagenet-vgg16.pth"

miscs:
  nb_classes: 1000
  min_pixel_value: -2.117904
  max_pixel_value: 2.248908
  reshape:
    - 3
    - 224
    - 224
  input_shape:
    - 3
    - 224
    - 224

art_attack_kwargs:
  fgsm_orig:
    norm: inf
    eps: 0.5
  fgsm_modf:
    norm: inf
    eps: 0.2
  pgd_orig:
    norm: inf
    eps: 0.5
  pgd_modf:
    norm: inf
    eps: 0.2
  bim_orig:
    eps: 0.5
  bim_modf:
    eps: 0.2
  cnw_orig: {}
  cnw_modf: {}
  deepfool_orig:
    epsilon: 0.001
    nb_grads: 10
  deepfool_modf:
    epsilon: 0.001
    nb_grads: 10
  elastic_orig:
    targeted: false
  elastic_modf:
    targeted: false

torch_attack_kwargs:
  fgsm_orig:
    norm: inf
    eps: 0.2
  fgsm_modf:
    norm: inf
    eps: 0.0001
  pgd_orig:
    norm: inf
    eps: 0.1
  pgd_modf:
    norm: inf
    eps: 0.0001
  bim_orig:
    norm: inf
    eps: 0.1
  bim_modf:
    norm: inf
    eps: 0.01
  cnw_orig:
    c: 0.01
    kappa: 0
    lr: 0.01
    steps: 1000
  cnw_modf:
    c: 1
    kappa: 0
    lr: 0.005
    steps: 1000
  deepfool_orig:
    steps: 5
  deepfool_modf:
    steps: 5
    overshoot: 0.0002
  elastic_orig:
    targeted: false
  elastic_modf:
    targeted: false
