model: MNIST

paths:
  root: /home/sweta/scratch/datasets/MNIST/

classifiers:
  mnist_ann_1: ./lightning_logs/mnist_classifier/checkpoints/epoch=9-step=9370.ckpt
autoencoders:
  ann_128: ./lightning_logs/mnist_ae_mse/checkpoints/epoch=9-step=9370.ckpt

miscs:
  nb_classes: 10
  min_pixel_value: 0.0
  max_pixel_value: 1.0
  reshape:
    - 28
    - 28
  input_shape:
    - 1
    - 784
