model: MNIST

dataset_path: ~/scratch/datasets/MNIST/

classifiers:
  mnist_ann_1: ./lightning_logs/mnist_classifier/checkpoints/epoch=9-step=9370.ckpt
  mnist_cnn_1: ./lightning_logs/mnist_cnn_classifier/checkpoints/epoch=49-step=42950.ckpt
autoencoders:
  ann_128: ./lightning_logs/mnist_ae_mse/checkpoints/checkpoint.ckpt
  cc_ann_100: ./lightning_logs/mnist_ccae_mse/checkpoints/checkpoint.ckpt
  cnn_32: ./lightning_logs/mnist_cnn_ae/checkpoints/epoch=19-step=8580.ckpt

miscs:
  nb_classes: 10
  min_pixel_value: 0.0
  max_pixel_value: 1.0
  reshape:
    - 28
    - 28
  input_shape:
    - 1
    - 784

art_attack_kwargs:
  fgsm_orig:
    norm: inf
    eps: 0.2
  fgsm_modf:
    norm: inf
    eps: 0.8
  pgd_orig:
    norm: inf
    eps: 0.8
  pgd_modf:
    norm: inf
    eps: 0.02
  bim_orig:
    norm: inf
    eps: 0.1
  bim_modf:
    norm: inf
    eps: 0.01
  cnw_orig: {}
  cnw_modf: {}
  deepfool_orig:
    epsilon: 0.001
    nb_grads: 10
  deepfool_modf:
    epsilon: 0.00001
    nb_grads: 5
  elastic_orig:
    targeted: false
  elastic_modf:
    targeted: false
